
name: "Teste de Action"
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    teste-action-job:
        permissions:
            issues: write
            pull-requests: write
        runs-on: ubuntu-lates
        name: Execução de Custom Action
        steps:
            - name: Adicionando Compentário
              uses: itamar-devops-pro/action-main@main
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário"